### ISSUE TITLE
error running lomorage docker image

### ISSUE THREAD

**Issue by rasplud** [lomorage/lomo-docker#9]
* *# sudo docker-compose -f docker-compose.vlan.yml up
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker-compose.vlan.yml'
* *

any advice from here for a noob please ?
cheers

**Comment by rasplud** [comment]
so i created a folder lomorage and the .yml file inside it and did run the command as below
* */lomorage# sudo docker-compose -f docker-compose.vlan.yml up
WARNING: The IMG variable is not set. Defaulting to a blank string.
WARNING: The HOME_MEDIA_DIR variable is not set. Defaulting to a blank string.
WARNING: The HOME_LOMO_DIR variable is not set. Defaulting to a blank string.
WARNING: The LOMOD_PORT variable is not set. Defaulting to a blank string.
WARNING: The AUTO_UPDATE_IMG variable is not set. Defaulting to a blank string.
ERROR: Version in "./docker-compose.vlan.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/* *

then my docker-compose.vlan.yml
* *version: "3.9"
services:
  lomo:
    image: ${IMG}
    container_name: lomorage
    privileged: true
    cap_add:
      - ALL
    volumes:
      - ${HOME_MEDIA_DIR}:/media
      - ${HOME_LOMO_DIR}:/lomo
      - /dev:/dev
    ports:
      - ${LOMOD_PORT}:${LOMOD_PORT}
    command: $LOMOD_PORT

  watchtower:
    image: ${AUTO_UPDATE_IMG}
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: lomorage --cleanup* *

i dont know what image name i should put and what to do with other dirs.
same for .env i dont what to do

please help welcome

**Comment by fuji246** [comment]
There is a example in https://github.com/lomorage/lomo-docker/blob/master/.env

you don't need to change the yml file, just change the ".env" file, put the ".env" file in the same directory with yml file.

If you are on arm device, use 
"IMG=lomorage/raspberrypi-lomorage:latest", 
"AUTO_UPDATE_IMG=containrrr/watchtower:armhf-latest",

otherwise if on x86/amd64, use
"IMG=lomorage/amd64-lomorage:latest"
"AUTO_UPDATE_IMG=containrrr/watchtower:amd64-latest",

set `HOME_MEDIA_DIR` and `HOME_LOMO_DIR` to the mounted hard drive, and make sure you have read/write access.

Change the following according to your network setup
```
NETWORK_TYPE=ipvlan # macvlan
NETWORK_INF=eth0
SUBNET=192.168.1.0/24
GATEWAY=192.168.1.1
VLAN_ADDR=192.168.1.79
```

**Comment by rasplud** [comment]
thanks a lot, gonna try that this morning , cant wait to try lomorage
